#This playbook prepares all nodes
## currently needed to enable root access on ubuntu servers

# enable root login without password
- hosts: all
  gather_facts: no
  vars:
    - ansible_ssh_user: ubuntu

  tasks:
    - name: Ensure python is available
      raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal aptitude)"
      register: output
      changed_when: output.stdout != ""
    - name: Disable remote root login
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin without-password"
      register: permitroot
    - name: Restart sshd
      service: name=ssh state=restarted
      when: permitroot|changed
  become: yes
