# clones of golden image
#

- name: prevent gc-cronjob from running on clones
  file: path=/etc/cron.d/seafile-gc state=absent

- name: "create {{ seafile_base_dir }}"
  file: name={{ seafile_base_dir }} state=directory

# configure seafile-data volume
- include: seafile-data_vol.yml
  when: use_separate_seafile_data_volume

- name: "sync timestamp changing stuff from golden image"
  synchronize:
    src: "{{ seafile_base_dir }}/"
    dest: "{{ seafile_base_dir }}"
    checksum: "yes"
    times: "no"
    rsync_opts:
      - "--delete"
      - "--include=/ccnet/***"
      - "--exclude=*"
  delegate_to: "{{ groups['master'][0] }}"
  notify:
    - Restart seafile

- name: "sync from golden image"
  synchronize:
    src: "{{ seafile_base_dir }}/"
    dest: "{{ seafile_base_dir }}"
    rsync_opts:
      - "--delete"
      - "--exclude=/logs"
      - "--exclude=/pids"
      - "--exclude=runtime/"
      - "--exclude=/ccnet"
      - "--exclude=/seafile-data/storage"
      - "--exclude=/seafile-data/httptemp"
      - "--exclude=/seafile-data/tmpfiles"
      - "--exclude=/seafile-data/webdavtmp"
      - "--exclude=/seahub-data/thumbnail"
      - "--exclude=pro-data/search"
      - "--exclude=pro/python/seafes/update.lock"
      - "--exclude=/{{ soffice_home }}"
      - "--exclude=*.pyc"
  delegate_to: "{{ groups['master'][0] }}"
  notify:
    - Restart seafile

- name: "create needed directories we can't sync correctly"
  file: >
    state=directory
    path="{{ seafile_base_dir }}/{{ item }}"
  with_items:
    - "pids"
    - "logs"
    - "seafile-server-latest/runtime"

# chown to seafile_user, if needed
- name: test seafile_user chown on clones
  file: >
    path="{{ seafile_base_dir }}/logs"
    owner={{ seafile_user }}
    state=directory
  register: logs_chown
  when: seafile_user is defined
  notify:
    - Restart seafile
# chown the rest, if logs didn't belong ro right user
- name: recursively chown remaining clone dirs
  shell: "chown -R {{ seafile_user }} {{ seafile_base_dir }}/{{ item }}"
  with_items:
    - "pids"
    - "logs"
    - "seafile-server-latest/runtime"
  when: logs_chown.changed

