# cluster initialization

- fail: msg="force_install not given. Run with -e force_install=true for a fresh install. THIS WILL REMOVE ALL CONTENTS from {{ seafile_base_dir }}"
  when: not force_install|default(False)

# wipe existing stuff for a clean start
- name: "remove existing {{ seafile_base_dir }}"
  file: name={{ seafile_base_dir }} state=absent

- name: "create {{ seafile_base_dir }}"
  file: name={{ seafile_base_dir }} state=directory

# unarchive installer
- name: extract seafile
  unarchive: >
    src="files/{{ installer_archive }}"
    dest="{{ seafile_base_dir }}"

- name: remove unnecessary java dependency check
  lineinfile: >
    dest="{{ seafile_base_dir }}/seafile-pro-server-{{ seafile_version }}/setup-seafile-mysql.sh"
    regexp="^check_java;"
    state=absent

- name: remove unnecessary locks from sql dump
  lineinfile: >
    dest="{{ seafile_base_dir }}/seafile-pro-server-{{ seafile_version }}/seahub/sql/mysql.sql"
    regexp="^(UN)?LOCK TABLES"
    state=absent

# run install module
- name: init seafile master install by module
  seafile_init: >
    path="{{ seafile_base_dir }}"
    subdir="seafile-pro-server-{{ seafile_version }}"
    seafile_mysql_user="{{ db_user }}"
    seafile_mysql_password="{{ db_pw }}"
    mysql_host="{{ db_server }}"
    mysql_port="{{ db_port }}"
    ccnet_db_name="{{ db_ccnet }}"
    seafile_db_name="{{ db_seafile }}"
    seahub_db_name="{{ db_seahub }}"
    central_conf_dir="{{ seafile_version | version_compare('5.0', operator='>=') | lower }}"
  when: seafile_version | version_compare('5.1.2', operator='<')

- name: init seafile master install by script call
  command: "{{ seafile_base_dir }}/seafile-pro-server-{{ seafile_version }}/setup-seafile-mysql.sh auto -n seafile -i {{ server_name }} -e 1 -o {{ db_server }} -t {{ db_port }} -u {{ db_user }} -w {{ db_pw }} -c {{ db_ccnet }} -s {{ db_seafile }} -b {{ db_seahub }} -q {{ db_allowed_hosts }}"
  when: seafile_version | version_compare('5.1.2', operator='>=')

# configure seafile-data volume
- include: seafile-data_vol_initial.yml
  when: use_separate_seafile_data_volume
