- name: "create {{ seafile_base_dir }}"
  file: >
    path="{{ seafile_base_dir }}/seafile-data"
    state=directory

- name: "create {{ seafile_base_dir }}/seafile-data"
  file: >
    path="{{ seafile_base_dir }}/seafile-data"
    owner="{{ seafile_user|default('root') }}"
    mode=0700
    state=directory

# guard for needed variables
- name: "Check for needed variables"
  fail: msg="Variable '{{ item }}' is not defined!"
  when: item not in vars
  with_items:
    - seafile_data_pvolumes

- name: "Create / extend volume group"
  lvg:
    vg: "seafile-data_vg"
    pvs: "{{ seafile_data_pvolumes }}"

- name: "Create / extend logical volume"
  lvol:
    vg: "seafile-data_vg"
    lv: "seafile-data_lv"
    size: "100%VG"
  register: lvol_seafile_data

- name: "Create / extend filesystem"
  filesystem:
    fstype: ext4
    dev: /dev/mapper/seafile--data_vg-seafile--data_lv
    resizefs: yes
  when: lvol_seafile_data.changed

- name: "Mount seafile-data"
  mount:
    fstype: ext4
    path: "{{ seafile_base_dir }}/seafile-data"
    src: /dev/mapper/seafile--data_vg-seafile--data_lv
    state: mounted
