- name: Create init.d script
  template: >
    src=init-seafile-server.j2
    dest=/etc/init.d/seafile-server
    owner=root
    group=root
    mode=0755
  notify:
    - Restart seafile

- name: Create upstart job
  copy: >
    src=seafile-server.conf
    dest=/etc/init/
    owner=root
    group=root
    mode=0644

- name: Create systemd service
  template: >
    src=seafile-server.service.j2
    dest=/etc/systemd/system/seafile-server.service
    owner=root
    group=root
    mode=0755
  notify:
    - Restart seafile

- name: Enable seafile-server on boot
  service: name="seafile-server" enabled="yes"
