seahub_disable_throttling: no
ssl_nodes: no
# decrypt ssl at loadbalancer
ssl_dec_loadbalancer: yes
webserver: "apache"
use_shibboleth: no
use_ldap: no
email_replace_from_email: False
email_add_reply_to_header: False
admin_error_email_include_html: False

#password
#password options. set true to use
pw_options: False
pw_repo_min_length: 8
pw_user_min_length: 6
pw_strength_level: 3
pw_user_strong_password_required: False

#thumbnail options
thumbnail_options: True
thumbnail_root: "{{ seafile_base_dir }}/seahub-data/thumbnail/thumb/" 
thumbnail_extension: png
thumbnail_default_size: 24
thumbnail_preview_default_size: 100

#session options
session_cookie_age: "60 * 60 * 24 * 7 * 2"
session_save_every_request: False
session_expire_at_browser_close: False
session_force_server_crypto: True

#ccnet.conf
ccnet_general_user_name: filesync
ccnet_client_port: 13419

#seafile.conf
seafile_network_port: 12001
seafile_fileserver_port: 8082
seafile_maximum_zip_dir_size: 200

#database defaults
db_allowed_hosts: '%'

# language / location
time_zone: Europe/Berlin
lang_code: en

# background node settings
soffice_home: "soffice-home"

# configstack settings
restart_seafile_on_changes: True

# GUI settings
show_traffic: True
share_link_password_min_length: 8
enable_resumable_fileupload: False
enable_guest_invitation: False

# Server settings
enable_wiki: False

# Libreoffice Online settings
libreoffice_webapp: False
libreoffice_webapp_host: "{{ hostvars[groups['background'][0]]['ansible_default_ipv4']['address'] }}"
libreoffice_webapp_base_url: 'https://{{ libreoffice_webapp_host }}:9980/hosting/discovery'

# internal settings
fastcgi_timeout: 60
max_open_files: 30000
use_separate_seafile_data_volume: False


# backends
block_backend_name: ceph
commit_backend_name: ceph
fs_backend_name: ceph
# ceph backend
ceph_config: /etc/ceph/ceph.conf
ceph_client_id: seafile
ceph_pool_block: seafile-blocks
ceph_pool_commit: seafile-commits
ceph_pool_fs: seafile-fs
# s3 backend
s3_bucket_block: my-block-objects
s3_bucket_commit: my-commit-objects
s3_bucket_fs: my-fs-objects
s3_sigv4: False

# logrotation
use_logrotate: yes
logrotate_interval: daily
logrotate_limit: 10
logrotate_seafile_service_options:
  - "{{ logrotate_interval }}"
  - missingok
  - "rotate {{ logrotate_limit }}"
  - compress
  - delaycompress
  - notifempty
  - sharedscripts

logrotate_config:
  - name: seafile
    path: "{{ seafile_base_dir }}/logs/seafile.log"
    options: "{{ logrotate_seafile_service_options }}"
    scripts:
      postrotate: "[ ! -f {{ seafile_base_dir }}/pids/seaf-server.pid ] || kill -USR1 `cat {{ seafile_base_dir }}/pids/seaf-server.pid`"
  - name: seafile-init
    path: "{{ seafile_base_dir }}/logs/seafile.init.log"
    options: "{{ logrotate_seafile_service_options }}"
  - name: ccnet
    path: "{{ seafile_base_dir }}/logs/ccnet.log"
    options: "{{ logrotate_seafile_service_options }}"
    scripts:
      postrotate: "[ ! -f {{ seafile_base_dir }}/pids/ccnet.pid ] || kill -USR1 `cat {{ seafile_base_dir }}/pids/ccnet.pid`"
  - name: seahub-init
    path: "{{ seafile_base_dir }}/logs/seahub.init.log"
    options: "{{ logrotate_seafile_service_options }}"
  - name: seahub
    path: "{{ seafile_base_dir }}/logs/seahub.log"
    options: "{{ logrotate_seafile_service_options }}"
  - name: seahub-requests
    path: "{{ seafile_base_dir }}/logs/seahub_django_request.log"
    options: "{{ logrotate_seafile_service_options }}"
  - name: seafdav
    path: "{{ seafile_base_dir }}/logs/seafdav.log"
    options: "{{ logrotate_seafile_service_options }}"
  - name: shibboleth
    path: "/var/log/shibboleth/*.log"
    options: "{{ logrotate_seafile_service_options }}"
    scripts:
      postrotate: "touch /etc/shibboleth/shibboleth2.xml > /dev/null"
  - name: apache2
    path: "/var/log/apache2/*.log"
    options:
      - "{{ logrotate_interval }}"
      - missingok
      - "rotate {{ logrotate_limit }}"
      - compress
      - delaycompress
      - notifempty
      - create 640 root adm
      - sharedscripts
    scripts:
      postrotate: |2
        if /etc/init.d/apache2 status > /dev/null ; then \
                /etc/init.d/apache2 reload > /dev/null; \
            fi;
      prerotate: |2
        if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
                run-parts /etc/logrotate.d/httpd-prerotate; \
            fi; \
  - name: nginx
    path: "/var/log/nginx/*.log"
    options:
      - "{{ logrotate_interval }}"
      - missingok
      - "rotate {{ logrotate_limit }}"
      - compress
      - delaycompress
      - notifempty
      - create 640 www-data adm
      - sharedscripts
    scripts:
      postrotate: "invoke-rc.d nginx rotate >/dev/null 2>&1"
      prerotate: |2
        if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
                run-parts /etc/logrotate.d/httpd-prerotate; \
           fi \


# settings for background node
bg_logrotate_config:
  - name: search indexer
    path: "{{ seafile_base_dir }}/logs/index.log"
    options: "{{ logrotate_seafile_service_options }}"
  - name: email sender
    path: "{{ seafile_base_dir }}/logs/seahub_email_sender.log"
    options: "{{ logrotate_seafile_service_options }}"
  - name: seafile-background-init
    path: "{{ seafile_base_dir }}/logs/seafile-background.init.log"
    options: "{{ logrotate_seafile_service_options }}"


memcached_backend: 'memcached'
memcached_backends:
  memached:
    packages:
      - python-memcache
    django_backend: 'django.core.cache.backends.memcached.MemcachedCache'
  pylibmc:
    packages:
      - python-pylibmc
    django_backend: 'django.core.cache.backends.memcached.PyLibMCCache'
  django-pylibmc:
    packages:
      - python-pylibmc
      - python-dev
      - libmemcached-dev
      - zlib1g-dev
    pip:
      - django-pylibmc
    django_backend: 'django_pylibmc.memcached.PyLibMCCache'

shibboleth_cert_rollover: no
# use shibboleth guest mapping (users not coming from the hosting institution get the guest role)
shibboleth_guests: no
# domain part of the hosting institutions eppn (like '@hu-berlin.de')
shibboleth_host_inst_suffix: 'UNDEF'
shibboleth_guest_role: 'guest'

# Fixes
# ldap workaround, see #940; enabled for backwards compatibility
ldap_lib_fix: True
# rados/ceph workaround, see #1720
rados_lib_fix: False

# set users static home folder
seafile_user_home: "/var/local/seafile"
