- name: Reload nginx
  service: name=nginx state=reloaded
- name: Restart apache
  service: name=apache2 state=restarted
- name: Restart shibd
  service: name=shibd state=restarted
  when: use_shibboleth
- name: Restart seafile
  service: name=seafile-server state=restarted
  when: restart_seafile_on_changes
